yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='main_posts'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
CSRF_FAILURE_VIEW = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

SYMBOLS_LIMIT = 15


class Group(models.Model):
    title = models.CharField(verbose_name='title', max_length=200)
    slug = models.SlugField(verbose_name='slug', unique=True)
    description = models.TextField(verbose_name='description')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='content', help_text='just text')
    pub_date = models.DateTimeField(verbose_name='date', auto_now_add=True)
    author = models.ForeignKey(User,
                               verbose_name='author',
                               on_delete=models.CASCADE,
                               related_name='posts')
    group = models.ForeignKey(Group,
                              verbose_name='group',
                              blank=True,
                              null=True,
                              on_delete=models.SET_NULL,
                              related_name='posts',
                              help_text='foreign key field')
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:SYMBOLS_LIMIT]

    class Meta:
        ordering = ['-pub_date']


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    author = models.ForeignKey(User,
                               verbose_name='author',
                               on_delete=models.CASCADE,
                               related_name='comments')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return self.text[50]


class Follow(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='follower')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='following')

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from .forms import PostForm, CommentForm
from .models import Post, Group, User, Comment, Follow
from django.views.decorators.cache import cache_page
from django.contrib.auth.models import User


POST_QUANTITY = 10


def index(request):
    post_list = Post.objects.select_related('author', 'group')
    paginator = Paginator(post_list, POST_QUANTITY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, POST_QUANTITY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):

    username = get_object_or_404(User, username=username)
    user_posts = Post.objects.filter(author=username)
    total_num_posts = user_posts.count
    paginator = Paginator(user_posts, POST_QUANTITY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = False
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user,
            author=username
        ).exists()

    context = {
        'username': username,
        'page_obj': page_obj,
        'total_num_posts': total_num_posts,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post_number = Post.objects.filter(
        author=post.author).count()
    form = CommentForm(request.POST or None)
    comments = Comment.objects.filter(post=post)

    context = {
        'post': post,
        'posts': post_number,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required()
def post_create(request):
    form = PostForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', request.user)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post,
                    )
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)

    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.select_related('author', 'group').filter(
        author__following__user=request.user)
    paginator = Paginator(posts, POST_QUANTITY)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    if author != user:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    user_follower = get_object_or_404(
        Follow,
        user=request.user,
        author__username=username
    )
    user_follower.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
  <body>
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if is_edit %} Добавить запись {% else %} Редактировать запись {% endif %}
              </div>
              <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                    {{ form }}

                  <div class="form-group row my-3 p-3">
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">{% if is_edit %}
                      Сохранить {% else %} Добавить {% endif %}
                    </button>

                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>

  </body>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Посты избранных авторов
{% endblock %}
{% csrf_token %}
{% block content %}
<div class="container">
{% include 'includes/switcher.html' %}
    <h1>Последние обновления избранных авторов</h1>
    {% for post in page_obj %}
    <article>
        <ul>
            <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
            <li>
                Дата публикации: {{ post.pub_date }}
            </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
            {{ post.text|linebreaksbr }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
    </article>
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% else %}
    <a href="#">записи не присвоили группу :(</a>
    {% endif %}
    <p>
    {% if not forloop.last %}
    <hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/group_list.html
  {% extends 'base.html' %}
  {% load thumbnail %}
  {% block title %} {{ group }} {% endblock %}
  {% block header %}{{ group }}{% endblock %}
  {% block content %}
  <h1>{{ group }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}

  <ul>
      <li>Автор: {{ post.author.get_full_name }}</li>
      <li>Дата публикации: {{ post.pub_date|date:"d E Y"}}</li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p>
  <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
    {% block title %}
    <title>Последние обновления на сайте.</title>
    {% endblock %}
    {% block content %}
    <h1>Последние обновления на сайте.</h1>
    {% for post in page_obj %}

    <div>
    <ul>
        <li>Автор: {{ post.author.get_full_name }}</li>
        <li>Дата публикации: {{ post.pub_date|date:"d E Y"}}</li>
    </ul>

{% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
    <p>{{ post.text }}</p>
    {% if post.group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a><br>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
   {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
        {% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:main_posts' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}
  </div>
  {% endfor %}
  {% include 'includes/paginator.html' %}
  {% endblock %}

yatube/templates/posts/post_detail.html
  {% extends 'base.html' %}
  {% load thumbnail %}
    {% block title %}
    <title> post.text|slice:":30" </title>
  {% endblock %}
{% block content %}
  <body>

    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y"}}
            </li>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}
            </img>
            {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group.title }}
              <br>
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
              {% endif %}
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }} {{ post.author.username }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post_number }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
            <li class="list-group-item"><a href="{% url 'posts:post_edit' post.id %}">
                Редактировать запись
              </a></li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
           {{ post.text }}
          </p>
          <!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
      {% endfor %}
    </div>
        </article>
      </div>
    </main>

  </body>
{% endblock %}

yatube/templates/posts/profile.html
  {% extends 'base.html' %}
  {% load thumbnail %}
    {% block title %}
  <title> post.author </title>
      {% endblock %}
  {% csrf_token %}
{% block content %}
  <body>
    <main>
      <div class="container py-5">
        <h1>Все посты пользователя: {{ username }} </h1>
        <h3>Всего постов: {{ total_num_posts }} </h3>
          {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' username %}" role="button"
      >
        Подписаться
      </a>
   {% endif %}
        </div>
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }} <br>
              <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y"}}
            </li>
          </ul>

{% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
          <p>
          {{ post.text }}
          </p>

          <br>
        {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}

      <hr>
      {% endfor %}

    {% include 'includes/paginator.html' %}
    </main>

  </body>

{% endblock %}